language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: N/TvbptyaXfX3hRcoSJdLQqh1jvs/0fBnv0XeHTDvFMGrA+fNbArWkUkM/PMOMQCtKSE3ZhpBbE4/Vw4pRQyLDcW/aataY75kSyoAzciq4Q3keLR9IEwkQuGc3LKmP9dm65qxA459G8+vo7ngUWl+SuqLdf8JeUcCsdRz2yiLAvtSeiis9HTUnNLnBIHBgi3iiAK18QXuR30fAHC1KKGc8/bNmZKg7H5sz0tzMDEGTXt8lobnlTGdGpJrhmeV4EI0cR4lbiO2F/HokM3Vcsy+JRVVglc2Ntaxw98D0UKSX303kxgd1Yo+9Pwovbhytk7kjCXIha52ACDnOsmTT0bZyyPrnuVKqyaV7WYqow1UkZ0B02ytwoqsS0HUymNBLgCSQic1l9a0oGChfOz+r8oeYAREWNpVhJ7Gg5TwONpdwEXAV3pHb009qt81QePKUNeGjiKzQoF4ZrDovHKl1zIREYOeprvnLsdynfGB9izbHD8v82sxpox3Mmb0r4zG7inohBSjSFH+d9Cyak/KxbtUkLs5E0dJnl8G63+PiLoo9rVBv4NaKedV5npFSig0xVGEw/qr5pDpNuUrmYJYUoxGf5dB1qM0NoTGLssfhkU+2sWBsf1Eq5qdtE1AyDwltrrLfEh8MlQ78FbHvzcnB1pbtiDNKg368jrGAUPBq4UG9Q=
