language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
branches:
  only:
  - master
  - gh-pages
  - gh_pages
env:
  global:
    secure: NmWKW6L//9pGDooIZKx6wLwYjRSTYoknI3N9VKXCR4nZ08msSksYasvsHZi7Q3a/DZF8Wbdu2aTgDgNtbHoR6jzVZEKC9T45snpoWL7uKsZVp9qJg3+1nrsLwmlWt2Xg/qoSEICf3Kxev4n+c0lyIccG9WdqGnNrO8Mxl0pulp6w/KH1c7bcJjEsyXzWDDMj81DIQyMND8EIp9WvQTPzRjluGfmZKtXiaDqrQeTpyM9DBvLVYHYNfKeFmjWSUCdTxAZgMu+uvAk8Jc8rjFWBxP9WBshiw5aewS6mHTeiNW28cd3dFRoQ+QbROFKRbitIwcMbr7CW771F+RSCn9/hqR6OjcV/iuq+xfffVTI4VGSOKFKjZpNosS/w+tVXDq/+XWoZKZWP4XBpIA0IrFgugg4aCzCjY6z1ocZgJVFXVb588AeCFKpV6YQK0GHH1633yD7SG1Yun6JdByZE3HFExva+1iKqwdlRmA99GD/0vD+FDM8YweD57TTKbSNUOx/lb7aAjDtTVkrFhBlqZVxB6HC9hco5UrnCjmEfREtC/x5B+8Thsj8cismpaVgHR1M4u7Lr82BCTjk8N03FLAm+9JfY7j8NRnd6mNEPKBiCb+XEUT2JGT/WDwqV0elSxR2pyM60AL2m+OMJQtx5S9IaUMuSLxfh4xkalDnKTKnY1Mg=
