language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: Aus4kIkuMzut9QzSEqBxpRRZqW982U/YLOBvUwxnGc1dHL9HnJ3TWEMQ1bDq7bg4PVAXlRaINLUkvKns+S4ahdlYRf6pC85PzLCoyI1lwKeK/HbFcE4ANQJRJnm1P9BE9qChEyzN2lwJ2O8xW0kDAftGP790vDm1jPgfLJleAXGnqF3w0k33BIMnUUY57wFVfHwyVQ02LLZXpX3/Go6aaBaKgxErsPEao9ILTXpJ4H8MvXAXmPujdrDgQ+/CFeUe4L/eEHCJmgVAPBc2qhQpXAp6POc0RHAXn3Tkq4tKJ6rUHKTdPAUIJbNWDIOp2X7LZFdl/1VIh6jWWNzV+aP9CPWj+jUuNof4CP6PC2VD4EaYUeIyYVZZXT7fnNM0oACjcWZWdRYoGm/wYQU5vagnjXPmKk21PqGzPTUOUo8DlzgLunoe1BOj/vd6JHDC446GUabxwz+X+84/HskI4Rd2aXt/SAiZocK36Wyb0a/+V9lLxBw4GZl0+B1i3fQGQo+yE8neWV57yw3mS72h7wVVG46CRi1KsREZ3GCawTVmaPsFDUPeHdrg43PZrk+D1xWSfc440wUCDwP2kzlz8uV1eHwmSa8/HayUa7uzEeftqDySoU2Wlhh3KhaJa0FkrUGubhy5eZCgsp8ShR+RRrik6vnnBgODiuriLivyX5NFus8=
